Add Owner Field to Monitor Config
getsentry/sentry-elixir pull request #829
Opened 2024-12-06 11:33 UTC by savhappy

Small addition that adds the `:owner` field to a check-in's monitor_config

2024-12-06 13:43 UTC, solnic approved these changes

2024-12-06 13:47 UTC, whatyouhide requested changes
I’m not sure this will be very useful without a way to set this per job on the Oban and Quantum integrations. Any ideas for the API?

2024-12-06 13:47 UTC, whatyouhide commented on lib/sentry/check_in.ex
> +                optional(:owner) => String.t()
**Blocking**: we need to mention that this is a new field available from the next version.

2025-05-06 12:59 UTC, Miradorn commented
> @savhappy any chance we can get this back into shape? 🙃

i think this was solved already in https://github.com/getsentry/sentry-elixir/pull/879 , right?

2025-05-06 13:10 UTC, closed without merging