Support for transactions
getsentry/sentry-elixir pull request #842
Opened 2024-12-27 12:13 UTC by solnic

2024-12-30 22:25 UTC, whatyouhide requested changes
Lots of comments, sorry 😄

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/envelope.ex
> +            Attachment.t() | CheckIn.t() | ClientReport.t() | Event.t() | Transaction.t()
The `...` means a non-empty list, not sure why it was removed?

```suggestion
            Attachment.t() | CheckIn.t() | ClientReport.t() | Event.t() | Transaction.t(), ...
```

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/envelope.ex
> +  @spec from_transaction(Sentry.Transaction.t()) :: t()
You aliased it 🙃 

```suggestion
  @spec from_transaction(Transaction.t()) :: t()
```

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/envelope.ex
> +        header = ~s({"type": "transaction", "length": #{byte_size(encoded_transaction)}})
Less bytes for free 🙃 

```suggestion
        header = ~s({"type":"transaction","length":#{byte_size(encoded_transaction)}})
```

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/options.ex
> +  @send_transaction_opts_schema NimbleOptions.new!(@send_transaction_opts_schema_as_keyword)
We don't need both and the `merge(_, [])` I think. Just go with

```suggestion
  @send_transaction_opts_schema NimbleOptions.new!(@@common_opts_schema_as_keyword)
```

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/options.ex
> +  @common_opts_schema_as_keyword [
Can you link to the docs that say that sample rate and before_send callbacks don't applly to transactions?

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/transaction.ex
> +defmodule Sentry.Transaction do
This needs docs

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/transaction.ex
> +    :span_id,
```suggestion
  defstruct @enforce_keys ++ [
```

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/transaction.ex
> +  @enforce_keys ~w(event_id span_id spans)a
Same number of characters and easier for readers less familiar with Elixir. Not a long list, so I don't think `~w` is worth it 🙃 

```suggestion
  @enforce_keys [:event_id, :span_id, :spans]
```

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/transaction.ex
> +  def new(attrs) do
Needs to be `@doc false` too I think?

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/transaction.ex
> +defmodule Sentry.Span do
Should this go under `Sentry.Interfaces`?

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/transaction.ex
> +defmodule Sentry.Span do
Also, docs

2024-12-30 22:25 UTC, whatyouhide commented on lib/sentry/transaction.ex
> +    {[root_span], child_spans} = Enum.split_with(transaction.spans, &is_nil(&1.parent_span_id))
I’m not super comfy with this. I think we should make illegal states unrepresentable if possible, so possibly have a `:root_span` and `:child_spans` fields maybe?

2025-01-03 14:20 UTC, solnic commented on lib/sentry/transaction.ex
> +    {[root_span], child_spans} = Enum.split_with(transaction.spans, &is_nil(&1.parent_span_id))
@whatyouhide sorry but I'm not entirely sure what you mean here. My understanding is that the span without parent_span_id becomes the transaction with extra information and the rest of spans become its child spans. No?

2025-01-03 17:32 UTC, whatyouhide commented on lib/sentry/transaction.ex
> +    {[root_span], child_spans} = Enum.split_with(transaction.spans, &is_nil(&1.parent_span_id))
I mean that a `transaction` struct with a `span` field where no spans have `parent_span_id == nil` *or* more than one spans have `parent_span_id == nil` is an **invalid transaction**, and we should never get to that state, right? If that is correct, then what I was suggesting here is that we store the root span and the child spans separately.

2025-01-03 20:30 UTC, solnic commented on lib/sentry/transaction.ex
> +    {[root_span], child_spans} = Enum.split_with(transaction.spans, &is_nil(&1.parent_span_id))
@whatyouhide oh so I need to double check this but IIRC a transaction with no child spans is accepted by Sentry

2025-01-07 14:24 UTC, solnic commented on lib/sentry/transaction.ex
> +    {[root_span], child_spans} = Enum.split_with(transaction.spans, &is_nil(&1.parent_span_id))
@whatyouhide I ended up reworking this struct via ef59c6f4598036377950b9dc53b1ee07a7df8e4d

2025-01-07 20:15 UTC, whatyouhide commented on lib/sentry/options.ex
> +  @common_opts_schema_as_keyword [
@solnic this is still pending.

2025-01-07 20:17 UTC, whatyouhide reviewed
Few more comments.

2025-01-07 20:17 UTC, whatyouhide commented on lib/sentry/transaction.ex
> +            event_id: <<_::256>>,
```suggestion
            event_id: UUID.t(),
```

2025-01-07 20:17 UTC, whatyouhide commented on lib/sentry/transaction.ex
> +            spans: [Span.t()],
A transaction without spans is ok?

2025-01-07 20:17 UTC, whatyouhide commented on lib/sentry/client.ex
> +    })
Can you elaborate on why this is necessary?

2025-01-08 09:05 UTC, solnic commented on lib/sentry/client.ex
> +    })
@whatyouhide I just followed what we do for events, and since a transaction is an event + span info, then I thought it's a good idea to add platform and sdk information too. I'm not sure if it's strictly required though - I'll double check it.

2025-01-08 09:06 UTC, solnic commented on lib/sentry/transaction.ex
> +            spans: [Span.t()],
@whatyouhide yes! the only really required piece of span information is meant to go to context.trace which is why I defined it as a required map in the type spec. spans list is only needed when you have child spans, and that's not always the case.

2025-01-21 09:51 UTC, solnic commented on lib/sentry/options.ex
> +  @common_opts_schema_as_keyword [
@whatyouhide sorry but link to what docs? Are you asking to write these docs and link to them?

2025-01-22 08:34 UTC, whatyouhide commented on lib/sentry/options.ex
> +  @common_opts_schema_as_keyword [
No, I’m asking where you found the information that `sample_rate` and `before_send` callbacks don't apply to transactions. As in, docs on the Sentry website that I can go read 😄

2025-01-22 13:23 UTC, solnic commented on lib/sentry/options.ex
> +  @common_opts_schema_as_keyword [
@whatyouhide oh, so I just didn't initially add support for these options. Transaction sampling [is a thing](https://develop.sentry.dev/application-architecture/dynamic-sampling/fidelity-and-biases/#transaction-sampling) in Sentry, so we should support it; and for consistency and feature-completion we should also support callbacks.

I just added support for all three options. One thing we might want to consider is deprecating after_send_event in favor of after_send though.

2025-01-26 09:11 UTC, whatyouhide approved these changes

2025-01-26 09:11 UTC, merged